name: Deploy to gh-pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout'
      - uses: 'actions/setup-node'
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
